
CXXFLAGS = -g -DDEBUG -Wall
#CXXFLAGS = -O2 -Wall
#LDLIBS = -lm

PROGS=tzx2pzx

all: $(PROGS)

tzx2pzx: tzx2pzx.o tzx.o pzx.o
	$(LINK.cpp) $^ $(LOADLIBES) $(LDLIBS) -o $@

clean:
	rm -rf *.o *~

tidy: clean
	rm -rf $(PROGS)

archive:
	tar czvf ../tzx2pzx.tar.gz *.cpp *.h Makefile

dep:
	sed -n -e '1,/^TOUCH=/ p' <Makefile >Makefile.new
	./mkdep >>Makefile.new
	mv Makefile.new Makefile

# generated by mkdep

TOUCH=touch
pzx.o : pzx.cpp buffer.h pzx.h
tzx.o : tzx.cpp endian.h pzx.h tzx.h
tzx2pzx.o : tzx2pzx.cpp buffer.h pzx.h tzx.h
buffer.h : debug.h endian.h
	$(TOUCH) $@
endian.h : types.h
	$(TOUCH) $@
pzx.h : buffer.h
	$(TOUCH) $@
tzx.h : types.h
	$(TOUCH) $@
